language: node_js
node_js: stable

install:
  - npm install -g gulp
  - npm install -g hexo-cli
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name “linran"
  - git config user.email "linran@live.com”
  - git add .
  - git commit -m “Update docs with TRAVIS-CI.”
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - doc
env:
  global:
    - GH_REF: https://github.com/linraner/linraner.github.io.git