language: node_js
node_js: 
  - "8.11.4"


cache:
  directories:
    - node_modules
    

install:
  - npm install -g hexo
  - npm install
  
  
 before_script:
  - npm install hexo-deployer-git --save
  - npm install hexo-asset-image --save
  - npm install mocha --save
  - git clone --branch master https://github.com/linraner/linraner.github.io.git

script:
  - hexo clean
  - hexo g


after_script:
  - cd ./public
  - git init
  - git config user.name "linran"  
  - git config user.email "linran@live.com" 
  - git add .
  - git commit -m "update by Travis-CI"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master 

branches:
  only:
  - doc
env:
    global:
        - GH_REF: https://github.com/linraner/linraner.github.io.git
           
